version = 0.1

[default.build.parameters]
use_container = false

[default.deploy.parameters]
resolve_s3 = true
region = "us-east-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
